[package]
name = "aws_core"
version = "0.2.0"
authors = ["Nathan Fuchs <fuchsnj@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.16"
chrono = "0.2.16"
hyper = "0.7"
regex = "0.1.41"
xml-rs = "0.1.26"
url = "0.2.37"
openssl = "0.7"
time = "0.1.32"